FROM node:18-alpine

WORKDIR /app

# Copy package.json files
COPY package*.json ./
COPY packages/server/package*.json ./packages/server/
COPY packages/shared/package*.json ./packages/shared/

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY packages/server ./packages/server
COPY packages/shared ./packages/shared

# Build shared package
RUN npm run build -w packages/shared

# Expose the server port
EXPOSE 3001

# Start the server
CMD ["npm", "run", "start:server"]
