FROM node:18-alpine

WORKDIR /app

# Copy package.json files
COPY package*.json ./
COPY packages/client/package*.json ./packages/client/
COPY packages/shared/package*.json ./packages/shared/

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY packages/client ./packages/client
COPY packages/shared ./packages/shared

# Build shared package
RUN npm run build -w packages/shared

# Expose the client port
EXPOSE 3000

# Start the client
CMD ["npm", "run", "start:client"]
